In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from joblib import dump

In [2]:
# Membaca data
data = pd.read_csv('fish_data.csv')

In [3]:
# Memisahkan fitur (atribut) dan target (label)
attribut = data[['length', 'weight', 'w_l_ratio']]
target = data['species']

In [4]:
# Membagi data menjadi data latih (80%) dan uji (20%)
x_train, x_test, y_train, y_test = train_test_split(attribut, target, test_size=0.20, random_state=0)

In [5]:
# Standarisasi data menggunakan StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [6]:
# Hyperparameter tuning untuk Perceptron
clf = Perceptron(max_iter=2000, eta0=0.01, tol=1e-4, random_state=0, early_stopping=True)
clf.fit(x_train_scaled, y_train)

Perceptron(early_stopping=True, eta0=0.01, max_iter=2000, tol=0.0001)

In [7]:
# Evaluasi Perceptron
prediksi_perceptron = clf.predict(x_test_scaled)
accuracy_perceptron = accuracy_score(y_test, prediksi_perceptron) * 100
conf_matrix_perceptron = confusion_matrix(y_test, prediksi_perceptron)

In [8]:
print("=== Perceptron ===")
print(f"Akurasi: {accuracy_perceptron:.2f}%")
print("Confusion Matrix:")
print(conf_matrix_perceptron)

=== Perceptron ===
Akurasi: 80.76%
Confusion Matrix:
[[ 92   0   0   0   0   5   0   0   0]
 [  0  96   0   0   0   0   0   0   0]
 [  0   3  97   0   0   0   0   0   0]
 [  0   4  17  59   0   0   0   0   5]
 [  0   0   0   0  77   7   0   0   0]
 [  1   0   0   0   2  82   0   0   0]
 [  3   0   7   0   0   0  64   0   0]
 [  0   0 103   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  92]]


In [9]:
# Cross-validation untuk Perceptron
cv_scores = cross_val_score(clf, x_train_scaled, y_train, cv=5)
print(f"Mean cross-validation accuracy (Perceptron): {cv_scores.mean() * 100:.2f}%")

Mean cross-validation accuracy (Perceptron): 70.77%


In [10]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=0)
mlp_clf.fit(x_train_scaled, y_train)
prediksi_mlp = mlp_clf.predict(x_test_scaled)
accuracy_mlp = accuracy_score(y_test, prediksi_mlp) * 100
conf_matrix_mlp = confusion_matrix(y_test, prediksi_mlp)

In [11]:
print("\n=== Multi-Layer Perceptron ===")
print(f"Akurasi: {accuracy_mlp:.2f}%")
print("Confusion Matrix:")
print(conf_matrix_mlp)


=== Multi-Layer Perceptron ===
Akurasi: 94.36%
Confusion Matrix:
[[97  0  0  0  0  0  0  0  0]
 [ 0 96  0  0  0  0  0  0  0]
 [ 0  0 87  0  0  0  0 13  0]
 [ 0  0  0 85  0  0  0  0  0]
 [ 0  0  0  0 84  0  0  0  0]
 [ 0  0  0  0  0 85  0  0  0]
 [ 0  0  0  0  0  0 74  0  0]
 [ 0  0 33  0  0  0  0 70  0]
 [ 0  0  0  0  0  0  0  0 92]]


In [12]:
# Menyimpan model terbaik (contoh: MLP) dan scaler ke file untuk aplikasi Streamlit
model_filename = 'mlp_fish_model.pkl'
dump(mlp_clf, model_filename)
print(f"\nModel MLP telah disimpan ke file: {model_filename}")


Model MLP telah disimpan ke file: mlp_fish_model.pkl


In [13]:
scaler_filename = 'scaler_fish_data.pkl'
dump(scaler, scaler_filename)
print(f"Scaler telah disimpan ke file: {scaler_filename}")

Scaler telah disimpan ke file: scaler_fish_data.pkl
